### ISSUE TITLE
VACS crashes on WIDTH directive

### ISSUE THREAD

**Issue by GertGr** [Dennis1000/VACS#1]
1. Not sure if tis is WIN32 related, but i experience a crash if i use the WIDTH directive (also with the LEFTMARGIN directive).
I run W7 64 bit with a 32 bit cmd window. I tried any combination of chars in front and back but as soon as i use WIDTH the assembler crashes. Title and Stitle work fine.

**Comment by Dennis1000** [comment]
Crash confirmed for 
```
WIDTH <expression>
LEFTMARG <expression>
PAGE <expression>
PGLEN <expression>
TABS <expression-list>
OFFS <expression>
```

**Comment by waltje** [comment]
Is there any update on this?

**Comment by ghost** [comment]
+1

**Comment by waltje** [comment]
I am not going to dive into old Pascal code, but elsewhere (in some other 2650 sources) I reada comment that the crash does not happen if the statement PAGE and/or WIDTH are not at thetop of the file, but halfway down a first page. Maybe below a TITLE directive- just guessing.
(I now use my own assembler)
Fred
   On Thursday, May 18, 2023 at 11:00:48 PM EDT, simmo456 ***@***.***> wrote:  
 
 


+1

**Comment by ghost** [comment]
Thank you.  This worked.

**Comment by Dennis1000** [comment]
Interesting. I couldn't follow the parsing of the WIDTH statement (it's highly optimized) but putting in somewhere in the middle initializes some buffers. Nice find!

**Comment by waltje** [comment]
> Interesting. I couldn't follow the parsing of the WIDTH statement (it's highly optimized)> but putting in somewhere in the middle initializes some buffers. Nice find!In the code we see:
            SetWidth:
              begin
                //OpcodePos := ErrorPntr;
                //MustBeExpr (0, $ffff);

                if EnaLineNum then
                  MustBeExpr (73, 255 - length (LMargStr))
                else
                  MustBeExpr (68, 255 - length (LMargStr));
                             { V1.10: minimum page width changed }
                if CurExpDef then
                  PageWidth := CurExpVal;
                if length (TitleLine) > PageWidth then
                  TitleLine[0] := AnsiChar (PageWidth);
                if length (SbTitleLine) > Pagewidth then
                  SbTitleLine[0] := AnsiChar (PageWidth);
                DontPrint := TRUE;
              end;
where the last part could crash, if TitleLine and/or SbTitleLine are still NIL.
Simple fix would be to
      tlLen, sbLen: Integer;      ..    tlLen := 0;
    if TitleLine <> NIL then     tlLen := length(TitleLine);
   and then
    if tlLen > PageWidth then      ...
etc.
Fred

**Comment by Dennis1000** [comment]
Thank you, I'll take look. Maybe I'm going to initialize the title/etc. buffers beforehand to avoid touching that code part ;-)

**Comment by Dennis1000** [comment]
Well, no, it crashes a few lines before:
MustBeExpr (68, 255 - length (LMargStr));
  ..Term..
  Result.IsUser := (CurIdent^.Typ = UserIdent);

and CurIdent isn't set yet.

But it helps me a lot having a workaround. Let's see if I can track down this error now.

**Comment by Dennis1000** [comment]
If anyone wants to try it
[asm32.zip](https://github.com/Dennis1000/VACS/files/11515959/asm32.zip)

**Comment by ghost** [comment]
yes, this works.   I have PAGELEN 255 and WIDTH 132 at the top of my main asm file.

PAGELEN 255
WIDTH 132
    TITLE   'DISKIOV3_PPIDE_TEST'	
    INCLUDE '2650_COMMON_DEFINITIONS.ASM'
    ORG     $0440
;
; SETUP THE CONSOLE, DISABLE THE ROM, INIT THE PPIDE, DISPLAY MENU		
BEGIN:
	LODI,R0	0               ;SET CONSOLE TO SERIAL
	STRA,R0	*CONSOLE_VEC	
	LODI,R2	HI MSG_TITLE
	LODI,R0	LO MSG_TITLE
	BSTA,UN	OUTSTR          ;PRINT THE TITLE MESSAGE
....

If you want me to do more thorough testing, let me know what you want me to try.

**Comment by Dennis1000** [comment]
Thanks for testing, official version1.24j will follow.

**Comment by Dennis1000** [comment]
@ simmo456 
> If you want me to do more thorough testing, let me know what you want me to try.

I'm quite sure there is another problem with that UserIdent parsing, but as I'm not really sure what it's
used for, it is somewhat difficult to test.

You may test the other mentioned directives (see second post above) - they are not crashing but
you may test if they do what they should do ;-) 

Thanks for your fast testing. Official version now released.
