### ISSUE TITLE
Problems with negative decimal constant

### ISSUE THREAD

**Issue by GertGr** [Dennis1000/VACS#2]
Negative values as a constant are not accepted . When starting a loop we often start with an index variable of -1 and an auto increment statement that update the register to 0 on first use. So i like to initialize R3 (in my case) to -1 decimal . This is not accepted by VACS . I can work around using $FF instead, but that is less clear to read.

**Comment by Dennis1000** [comment]
This is not trivial as it sounds to implement.  The source code uses as a range check like this:
`  MustBeExpr(0,255);`
while checking the range on these opcodes
`  Opcode,r v       (v = 0..255)`

I could change that to 
`   MustBeExpr(-128,255);`

which would translate negative values to their two's complement representation while maintaining the default binary representation with positive values.

```
1 = $01
0 = $00
-1 = $FF
-128 = $80

255 = $FF
128 = $80
```

**Comment by Dennis1000** [comment]
Ah well, was easier to do as expected. Changed the above mentionend `MustBeExpr(0,255)` to `MustBeExpr(-128,255)` and it works quite nice. Still need to look at other range checks as well.

```
0000 0500               lodi,r1     0         ;  $00
0002 0601               lodi,r2     1         ;  $01
0004 04FF               lodi,r0     -1        ;  $FF
0006 05FE               lodi,r1     -2        ;  $FE
0008 0680               lodi,r2     -128      ;  $80 
000A                    ;lodi,r2     -129      ; "Value out of range" error
000A 0680               lodi,r2     128       ;  $80
000C 06FF               lodi,r2     255       ;  $FF
```
