### ISSUE TITLE
Second ORG statement ignored

### ISSUE THREAD

**Issue by GertGr** [Dennis1000/VACS#4]
It seems as if the assembler ignores (silently) a second ORG statement in the source text .
This can be by design, but my code heavily depends on a table starting on a XX00 address. 
Good programming practice won't do so but it is a heritage project.

In the listing the ORG works fine, but the binary dump (.bin file) the space between last code and the org address is not filled up with 00 or FF but the code following the org neatly follows the code before. This is the code fragment:

08EE C2                   STRZ    R2
08EF 0FB00F               LODA,R0 *TEMQ,R3+
08F2 0F1057               LODA,R3 MCNT
08F5 7508                 CPSL    $08
08F7 17                   RETC,UN
08F8              
08F8 00                   DB      $00
08F9 2C2B2D232A   OPERANDS        DB      ',+-#*'
0900                      **org     $900**    ;               tabel searching relies   HERE
              -->  on fixed high byte
0900              
**0900** 5230202000F0 REGS    DB      'R0  ',$00,$F0  ;MNEMONIC , BASE OPCODE (6 BIT
              --> S),PROPERTIES
0906 5231202001F0         DB      'R1  ',$01,$F0          ;PROPERTIES : LAST FOU
              --> R BITS 08 04 02 01 ARE ABS , REL, IMM, REG
090C 5232202002F0         DB      'R2  ',$02,$F0  ;PROPERTEI : BIT 7 = PSEUDOCOD
              --> E
0912 5233202003F0         DB      'R3  ',$03,$F0
0918              
0918              
0918 5020202001F0 COND    DB      'P   ',$01,$F0
091E 5A20202000F0         DB      'Z   ',$00,$F0
0924 4E20202002F0         DB      'N   ',$02,$F0
092A 4C54202002F0         DB      'LT  ',$02,$F0
0930 4551202000F0         DB      'EQ  ',$00,$F0
0936 4754202001F0         DB      'GT  ',$01,$F0
093C 554E202003F0         DB      'UN  ',$03,$F0

**Comment by Dennis1000** [comment]
This should work, see `dist\examples\pageboundary.asm`

**Comment by Dennis1000** [comment]
I see a typo in that example
`  org     2000H                     ; we're now on $1000,`
should say
`org     2000H                     ; we're now on $2000,`

**Comment by Dennis1000** [comment]
oh. I see. the binary isn't filled - only the hex listing works.

**Comment by Dennis1000** [comment]
Fixed binary output with multiple org statements (works with -c parameter)
